baseURL = "https://jlpabon.github.io/"
languageCode = "en-us"
title = "Jose Luis Pabon Website"

theme = "academia-hugo"
# email = "test@example.com"
email_form = 0

# 1. Use relative URLs for all assets (CSS, JS, etc.)
relativeURLs = true

# 2. Tell the theme where the content is rooted for assets
[params]
  # This baseurl starts and ends with a slash and includes the repo name.
  baseurl = "/Websitejlpv1/"
