baseURL = "" # <--- Change to an empty string!
languageCode = "en-us"
title = "Jose Luis Pabon Website"

theme = "academia-hugo"
# email = "test@example.com"
email_form = 0

relativeURLs = true # This line must remain true!

## To get dark as the default add "dark" as a class to body.
## Still haven't found the configuration place for this.
