# Example: Deploy Hugo site to GitHub Pages workflow (update upload-artifact to v4)
# Adjust version pins and steps to match your existing workflow; the critical change is:
# actions/upload-artifact@v3  -> actions/upload-artifact@v4
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3' # set the Hugo version you need

      - name: Build
        run: hugo --minify

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
